### ISSUE TITLE
Query: Does this support multiple device run

### ISSUE THREAD

**Issue by vikramvi** [iheartradio/androidAutomation#12]
Hi,

Can you please clarify if this framework supports running test cases parallely on multiple device and/or emulators ?

Thanks & Regards,
Vikram

**Comment by danigol** [comment]
Currently it's only set up to hit a single device at a time. It's possible that this project will run on multiple devices in the future, though this isn't being directly investigated currently.

**Comment by vikramvi** [comment]
Thanks for clarification
